services:
  scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./jobs_project:/app/jobs_project
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://user:assignment@mongodb:27017/
      - MONGO_DB=scrapy_db
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=assignment
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: