FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
COPY jobs_project/ jobs_project/
COPY infra/ infra/
COPY query.py .
COPY scrapy.cfg .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["scrapy", "crawl", "json"]